"""Markdown report exporter."""

from typing import Optional
from datetime import timedelta

from .base import BaseExporter
from ..models import AnalysisResult


class MarkdownExporter(BaseExporter):
    """Export analysis results to Markdown format."""

    def export(self, result: AnalysisResult, output_path: Optional[str] = None) -> str:
        """Export to Markdown.

        Args:
            result: Analysis result
            output_path: Optional file path

        Returns:
            Markdown string or file path if written
        """
        lines = []

        # Title
        lines.append("# 🔍 Log Analysis Report")
        lines.append("")

        # Summary
        lines.append("## 📊 Summary")
        lines.append("")
        lines.append(f"- **Source File:** `{result.source_file}`")
        lines.append(f"- **Total Entries:** {result.total_entries:,}")
        lines.append(f"- **Analyzed Entries:** {result.analyzed_entries:,}")
        lines.append(f"- **Analysis Duration:** {result.analysis_duration:.2f}s")
        lines.append("")

        # Anomaly counts
        lines.append("### Anomalies")
        lines.append("")
        lines.append(f"| Metric | Count |")
        lines.append(f"|--------|-------|")
        lines.append(f"| Total | {result.anomaly_count} |")
        lines.append(f"| Critical | {len(result.critical_anomalies)} |")
        lines.append(f"| High Severity | {len(result.high_severity_anomalies)} |")
        lines.append("")

        # Statistics
        lines.append("## 📈 Statistics")
        lines.append("")
        lines.append(f"| Metric | Value |")
        lines.append(f"|--------|-------|")
        lines.append(f"| Error Rate | {result.error_rate * 100:.2f}% |")

        if result.average_response_time:
            lines.append(f"| Average Response Time | {result.average_response_time:.2f}ms |")

        if result.total_response_size:
            lines.append(f"| Total Response Size | {result.total_response_size:,} bytes |")

        lines.append("")

        # Log levels
        if result.log_level_counts:
            lines.append("### Log Level Distribution")
            lines.append("")
            lines.append("| Level | Count |")
            lines.append("|-------|-------|")
            for level, count in sorted(result.log_level_counts.items()):
                lines.append(f"| {level} | {count:,} |")
            lines.append("")

        # Anomalies
        lines.append("## ⚠️ Detected Anomalies")
        lines.append("")

        if result.anomalies:
            for i, anomaly in enumerate(result.anomalies[:50], 1):
                badge = self._get_badge(anomaly.severity_level.value)

                lines.append(f"### {i}. {badge} {anomaly.description}")
                lines.append("")

                lines.append(f"- **Type:** {anomaly.anomaly_type}")
                lines.append(f"- **Severity:** {anomaly.severity:.1f}/10")
                lines.append(f"- **Confidence:** {anomaly.confidence:.1%}")
                lines.append(f"- **Occurrences:** {anomaly.occurrence_count:,}")

                if anomaly.duration:
                    duration_str = str(timedelta(seconds=int(anomaly.duration)))
                    lines.append(f"- **Duration:** {duration_str}")

                if anomaly.context.get("metric"):
                    lines.append(f"- **Metric:** {anomaly.context['metric']}")

                if anomaly.pattern:
                    lines.append(f"- **Pattern:** `{anomaly.pattern[:80]}`")
                    lines.append(f"- **Frequency:** {anomaly.pattern_frequency:,}")

                lines.append("")
        else:
            lines.append("No anomalies detected. ✅")
            lines.append("")

        # Insights
        if result.insights:
            lines.append("## 💡 Actionable Insights")
            lines.append("")

            for insight in result.insights:
                lines.append(f"### 📌 {insight.title}")
                lines.append("")
                lines.append(f"**Category:** {insight.category} | **Priority:** {insight.priority.upper()}")
                lines.append("")
                lines.append(f"{insight.description}")
                lines.append("")
                lines.append(f"**Recommendation:** {insight.recommendation}")
                lines.append("")

                if insight.evidence:
                    lines.append("**Evidence:**")
                    for key, value in insight.evidence.items():
                        lines.append(f"- {key}: {value}")
                    lines.append("")

        # Footer
        lines.append("---")
        lines.append(f"*Generated by LogAnalyzer at {result.end_time.strftime('%Y-%m-%d %H:%M:%S')}*")

        markdown = "\n".join(lines)

        # Write to file if path specified
        if output_path:
            with open(output_path, 'w') as f:
                f.write(markdown)
            return output_path

        return markdown

    def _get_badge(self, severity: str) -> str:
        """Get markdown badge for severity level."""
        colors = {
            "CRITICAL": "🔴",
            "HIGH": "🟠",
            "MEDIUM": "🟡",
            "LOW": "🔵",
            "INFO": "⚪",
        }
        return colors.get(severity, "⚪")
