"""Plain text report exporter."""

from typing import Optional
from datetime import timedelta

from .base import BaseExporter
from ..models import AnalysisResult, SeverityLevel


class TextExporter(BaseExporter):
    """Export analysis results to plain text format."""

    def export(self, result: AnalysisResult, output_path: Optional[str] = None) -> str:
        """Export to plain text.

        Args:
            result: Analysis result
            output_path: Optional file path

        Returns:
            Text string or file path if written
        """
        lines = []

        # Header
        lines.append("=" * 80)
        lines.append("LOG ANALYSIS REPORT")
        lines.append("=" * 80)
        lines.append("")

        # Summary
        lines.append("SUMMARY")
        lines.append("-" * 40)
        lines.append(f"Source File:        {result.source_file}")
        lines.append(f"Total Entries:      {result.total_entries:,}")
        lines.append(f"Analyzed Entries:   {result.analyzed_entries:,}")
        lines.append(f"Analysis Duration:  {result.analysis_duration:.2f}s")
        lines.append("")

        # Statistics
        lines.append("STATISTICS")
        lines.append("-" * 40)
        lines.append(f"Error Rate:         {result.error_rate * 100:.2f}%")
        if result.average_response_time:
            lines.append(f"Avg Response Time:  {result.average_response_time:.2f}ms")
        if result.total_response_size:
            lines.append(f"Total Response Size: {result.total_response_size:,} bytes")

        lines.append("")
        lines.append("Log Levels:")
        for level, count in sorted(result.log_level_counts.items()):
            lines.append(f"  {level:12s}: {count:,}")
        lines.append("")

        # Anomalies
        lines.append("ANOMALIES DETECTED")
        lines.append("-" * 40)
        lines.append(f"Total: {result.anomaly_count}")
        lines.append(f"Critical: {len(result.critical_anomalies)}")
        lines.append(f"High Severity: {len(result.high_severity_anomalies)}")
        lines.append("")

        # Top Anomalies
        if result.anomalies:
            lines.append("TOP ANOMALIES")
            lines.append("-" * 40)

            for i, anomaly in enumerate(result.anomalies[:20], 1):
                lines.append(f"\n{i}. [{anomaly.severity_level.value}] {anomaly.description}")
                lines.append(f"   Type:        {anomaly.anomaly_type}")
                lines.append(f"   Severity:    {anomaly.severity:.1f}/10")
                lines.append(f"   Confidence:  {anomaly.confidence:.1%}")
                lines.append(f"   Occurrences: {anomaly.occurrence_count:,}")

                if anomaly.first_seen and anomaly.last_seen:
                    duration = anomaly.duration
                    if duration:
                        lines.append(f"   Duration:    {timedelta(seconds=int(duration))}")

                if anomaly.context.get("metric"):
                    lines.append(f"   Metric:      {anomaly.context['metric']}")

                if anomaly.pattern and anomaly.pattern_frequency:
                    lines.append(f"   Pattern:     {anomaly.pattern[:80]}")
                    lines.append(f"   Frequency:   {anomaly.pattern_frequency:,}")

        # Insights
        if result.insights:
            lines.append("\n")
            lines.append("ACTIONABLE INSIGHTS")
            lines.append("-" * 40)

            for i, insight in enumerate(result.insights, 1):
                lines.append(f"\n{i}. [{insight.category.upper()}] {insight.title}")
                lines.append(f"   Priority:    {insight.priority.upper()}")
                lines.append(f"   Description: {insight.description}")
                lines.append(f"   Recommendation: {insight.recommendation}")

                if insight.evidence:
                    lines.append(f"   Evidence:")
                    for key, value in insight.evidence.items():
                        lines.append(f"     - {key}: {value}")

        # Footer
        lines.append("\n")
        lines.append("=" * 80)
        lines.append(f"Generated by LogAnalyzer at {result.end_time.strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append("=" * 80)

        report = "\n".join(lines)

        # Write to file if path specified
        if output_path:
            with open(output_path, 'w') as f:
                f.write(report)
            return output_path

        return report
